#By AlexDeveloperUwU
name: Github Pages Publisher for VuePress

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.11.1]
        
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Instalación de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Intalación de paquetes
      run: npm ci
    - name: Generación de los archivos estáticos HTML
      run: npm run build
    - name: CD al directorio del resultado 
      run: cd ./src/.vuepress/
    - name: Publicación de la página en Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages
          folder: ./src/.vuepress/dist
